# Generated by Django 3.0.3 on 2020-04-21 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_society_post'),
        ('queries', '0004_remove_post_society'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='society',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Society'),
        ),
    ]
