# Generated by Django 3.0.4 on 2020-04-23 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_remove_society_whoallvoted'),
        ('users', '0002_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Discription', models.TextField()),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Society')),
                ('whoallvoted', models.ManyToManyField(related_name='Check_vote_once', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
