# Generated by Django 3.0.4 on 2020-04-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
