# Generated by Django 3.0.4 on 2020-04-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_auto_20200423_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='society',
            new_name='elections',
        ),
    ]
