# Generated by Django 3.0.4 on 2020-04-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_auto_20200423_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='votes',
            field=models.IntegerField(),
        ),
    ]
