# Generated by Django 3.0.4 on 2020-04-21 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='Pending_List',
            field=models.ManyToManyField(related_name='pending_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
