# Generated by Django 3.0.3 on 2020-04-21 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0004_remove_post_society'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='queries.Post'),
        ),
    ]
