# Generated by Django 3.0.4 on 2020-04-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_society_pending_list'),
        ('blog', '0003_remove_society_post'),
    ]

    operations = [
    ]
