# Generated by Django 3.0.4 on 2020-04-22 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_merge_20200422_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='whoallvoted',
            field=models.ManyToManyField(related_name='Check_vote_once', to=settings.AUTH_USER_MODEL),
        ),
    ]
