# Generated by Django 3.0.4 on 2020-04-23 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200423_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society',
            name='whoallvoted',
        ),
    ]
