# Generated by Django 3.0.4 on 2020-04-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_society_whoallvoted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='Participation_on',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='society',
            name='Voting_on',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='society',
            name='Voting_process_on',
            field=models.BooleanField(),
        ),
    ]
